services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    container_name: myapp
    command: pipenv run daphne myproject.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - .:/app
      - /home/vik/Pictures/Images:/app/media/images
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

volumes:
  pgdata: