# Generated by Django 4.2.14 on 2024-08-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='received_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
