# Generated by Django 4.2.14 on 2024-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_emailmessage_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
